# Generated by Django 5.1.2 on 2025-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subheading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Home', 'Home'), ('World', 'World'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Business', 'Business'), ('Science', 'Science'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Arts', 'Arts & Entertainment Desk')], default='Arts', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('href_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
